# Generated by Django 4.2.27 on 2026-01-21 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sauna_name", models.CharField(max_length=100, verbose_name="施設名")),
                ("sauna_time", models.IntegerField(verbose_name="サウナ(分)")),
                ("water_time", models.IntegerField(verbose_name="水風呂(秒)")),
                ("rest_time", models.IntegerField(verbose_name="外気浴(分)")),
                ("comment", models.TextField(blank=True, verbose_name="黙示録(メモ)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="観測日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
