# Generated by Django 4.2.27 on 2026-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="apocalypse_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="record",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="rest_time",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="sauna_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="sauna_time",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="water_time",
            field=models.IntegerField(default=60),
        ),
    ]
